spring.datasource.url = jdbc:postgresql://localhost:5432/wassali_web_application
spring.datasource.username = wiem
spring.datasource.password = wiem

spring.jpa.properties.hibernate,dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=haddad.iheb99@gmail.com
spring.mail.password=kplt rpht iqfy gyor


spring.session.timeout=3600
spring.session.jdbc.initialize-schema=ALWAYS
spring.session.jdbc.table-name=SPRING_SESSION

server.port = 8090


 



